# Generated by Django 6.0 on 2025-12-11 02:15

import django.core.validators
import locadora.validators.data_max_validator
import locadora.validators.ipva_atrasado_validator
import locadora.validators.ultima_revisao_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('Porsche', 'Porsche'), ('Ferrari', 'Ferrari'), ('Ford', 'Ford'), ('Lamborghini', 'Lamborghini'), ('Tesla', 'Tesla'), ('Bugatti', 'Bugatti')], help_text='Selecione a marca do carro', max_length=20, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Marca')),
                ('modelo', models.CharField(help_text='Informe o modelo do carro', max_length=20, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Modelo')),
                ('ano', models.IntegerField(help_text='Informe o ano do carro', verbose_name='Ano')),
                ('alugado', models.BooleanField(default=False, help_text='Marque se o carro está alugado', verbose_name='Alugado ?')),
                ('placa', models.CharField(help_text='Digite a placa do carro', max_length=7, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='Placa')),
                ('valor_diaria', models.DecimalField(decimal_places=2, help_text='Digite o valor da diária do carro', max_digits=10, validators=[django.core.validators.MinValueValidator(200)], verbose_name='Diária')),
                ('seguro', models.DecimalField(decimal_places=2, help_text='Digite o valor do seguro', max_digits=10, validators=[django.core.validators.MinValueValidator(50)], verbose_name='Seguro')),
                ('ultima_revisao', models.DateField(help_text='Informe a data da última revisão do carro', validators=[locadora.validators.data_max_validator.DataMaxValidator(), locadora.validators.ultima_revisao_validator.UltimaRevisaoValidator()], verbose_name='Revisão')),
                ('ipva', models.BooleanField(default=True, help_text='Marque se o IPVA está pago', validators=[locadora.validators.ipva_atrasado_validator.IpvaAtrasadoValidator()], verbose_name='IPVA')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
