# Generated by Django 6.0 on 2025-12-11 12:57

import django.core.validators
import locadora.validators.ano_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='ano',
            field=models.IntegerField(help_text='Informe o ano do carro', validators=[locadora.validators.ano_validator.AnoValidator], verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='placa',
            field=models.CharField(help_text='Digite a placa do carro', max_length=7, validators=[django.core.validators.MinLengthValidator(7, message='A placa deve conter 7 dígitos')], verbose_name='Placa'),
        ),
    ]
