# Generated by Django 6.0 on 2025-12-11 13:27

import locadora.validators.ano_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0002_alter_carro_ano_alter_carro_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='ano',
            field=models.IntegerField(help_text='Informe o ano do carro', validators=[locadora.validators.ano_validator.AnoValidator()], verbose_name='Ano'),
        ),
    ]
