# Generated by Django 5.0 on 2025-12-19 18:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(help_text='Insira o nome da cidade', max_length=50, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nome da cidade')),
                ('estado', models.CharField(help_text='Insira a sigla do Estado', max_length=2, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Estado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Esporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(help_text='Digite o nome do esporte', max_length=50, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nome do esporte')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(help_text='Digite o nome do clube', max_length=30, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nome do Clube')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(help_text='Insira o nome da pessoa', max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nome')),
                ('genero', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outro', 'Outro')], help_text='Selecione o gênero da pessoa', max_length=15, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Gênero')),
                ('idade', models.IntegerField(help_text='Insira a idade da pessoa', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)], verbose_name='Idade')),
                ('renda', models.DecimalField(decimal_places=2, help_text='Valor da renda mensal', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100000000.0)], verbose_name='Renda Mensal')),
                ('endereco', models.ForeignKey(help_text='Selecione a cidade', on_delete=django.db.models.deletion.RESTRICT, to='wrapper.cidade', verbose_name='Endereço')),
                ('esporte', models.ForeignKey(help_text='Selecione o esporte favorito', on_delete=django.db.models.deletion.RESTRICT, to='wrapper.esporte', verbose_name='Esporte favorito')),
                ('time', models.ForeignKey(help_text='Selecione o  time que a pessoa torce', on_delete=django.db.models.deletion.RESTRICT, to='wrapper.time', verbose_name='Time que torce')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
