# Generated by Django 5.0 on 2025-11-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Insira o nome do Atleta', max_length=50, verbose_name='Nome do Atleta')),
                ('esporte', models.CharField(help_text='Insira o nome do esporte', max_length=50, verbose_name='Nome do esporte práticado')),
                ('nascimento', models.DateField(help_text='Insira a data de nascimento', verbose_name='Data de nascimento do atleta')),
                ('email', models.EmailField(help_text='Insira o email', max_length=254, verbose_name='Insira o e-mail do atleta')),
                ('patrocinio', models.DecimalField(decimal_places=2, help_text='Insira o valor dos patrocionos', max_digits=5, verbose_name='Valor total de patrocinios do alteta')),
                ('premios', models.IntegerField(help_text='Insira a quantidade de prêmios ganhos', verbose_name='Total de prêmios')),
                ('nota', models.FloatField(help_text='Insira a nota do aluno', verbose_name='Notas do aluno')),
                ('aposentado', models.BooleanField(help_text='Atleta aposentado', verbose_name='Aposetado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exemplo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Insira o nome do Exemplo', max_length=50, verbose_name='Nome do Exemplo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
