# Generated by Django 5.0 on 2025-11-24 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemplo',
            name='idade',
            field=models.IntegerField(default=11, help_text='Idade do exemplo', validators=[django.core.validators.MinValueValidator(18, message='Idade mínima 18 anos'), django.core.validators.MaxValueValidator(100, message='Idade máxima 100 anos')], verbose_name='Insira a idade do exemplo'),
            preserve_default=False,
        ),
    ]
