# Generated by Django 5.0 on 2025-11-24 19:03

import digital.validators.funcoes
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0002_exemplo_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemplo',
            name='nascimento',
            field=models.DateField(blank=True, help_text='Insira a sua data de nascimento', null=True, validators=[digital.validators.funcoes.validar_maioridade], verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='exemplo',
            name='idade',
            field=models.IntegerField(help_text='Idade do exemplo', validators=[django.core.validators.MinValueValidator(18, message='Idade mínima 18 anos'), django.core.validators.MaxValueValidator(100, message='Idade máxima 100')], verbose_name='Insira a idade do exemplo'),
        ),
    ]
