# Generated by Django 5.0 on 2025-11-24 19:35

import digital.validators.nome_proibido_validator
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0003_exemplo_nascimento_alter_exemplo_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemplo',
            name='apelido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exemplo',
            name='nome',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, message='No mínimo o nome deve conter 2 caracteres'), digital.validators.nome_proibido_validator.NomeProibidoValidator(nomes_proibidos=['admin'])]),
        ),
    ]
