# Generated by Django 5.0 on 2025-11-28 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0004_exemplo_apelido_alter_exemplo_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemplo',
            name='campus',
            field=models.CharField(blank=True, help_text='Digite o campus de sua escolha', max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Campus'),
        ),
    ]
