# Generated by Django 5.0 on 2025-11-28 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0005_exemplo_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemplo',
            name='campus',
            field=models.CharField(blank=True, choices=[('POA', 'Campus Porto Alegre'), ('Restinga', 'Campus Restinga'), ('Rolante', 'Campus Rolante'), ('POA Zona Norte', 'Campus POA Zona Norte')], default='POA', help_text='Digite o campus de sua escolha', max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Campus'),
        ),
    ]
