# Generated by Django 5.0 on 2025-12-01 19:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0006_alter_exemplo_campus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escritorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Insira o número da sala', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Número')),
                ('andar', models.IntegerField(help_text='Insira o andar da sala', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Andar')),
                ('predio', models.CharField(choices=[('Torre Sul', 'Torre Sul'), ('Torre Norte', 'Torre Norte'), ('Administrativo', 'Administrativo'), ('Prédio A', 'Prédio A')], help_text='Selecione o prédio da sala', max_length=30)),
                ('campus', models.CharField(choices=[('POA', 'Campus Porto Alegre'), ('Restinga', 'Campus Restinga'), ('Rolante', 'Campus Rolante'), ('POA Zona Norte', 'Campus POA Zona Norte')], help_text='Selecione o campus da sala', max_length=30, verbose_name='Campus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(help_text='Insira a matrícula do Professor', max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='Matrícula')),
                ('nome', models.CharField(help_text='Digite o nome do Professor', max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('area', models.CharField(help_text='Digite a área do professor', max_length=50, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Área')),
                ('admissao', models.DateField(help_text='Digite a data de admissão', verbose_name='Admissão')),
                ('email', models.EmailField(help_text='Digite o e-mail profissional do professor', max_length=254, unique=True, verbose_name='E-mail')),
                ('aposentado', models.BooleanField(default=False, help_text='Marque se o professor está aposentado', verbose_name='Aposentado ?')),
                ('horario_inicial', models.TimeField(help_text='Digite a hora de início do trabalho', verbose_name='Hora de início do trabalho')),
                ('horario_final', models.TimeField(help_text='Digite a hora de término do trabalho', verbose_name='Hora de término do trabalho')),
                ('escritorio', models.OneToOneField(help_text='Escolha o escritório', on_delete=django.db.models.deletion.RESTRICT, to='digital.escritorio', verbose_name='Escritório')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
