# Generated by Django 5.0 on 2025-12-01 19:54

import digital.validators.admissao_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0007_escritorio_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='admissao',
            field=models.DateField(help_text='Digite a data de admissão', validators=[digital.validators.admissao_validator.AdmissaoValidator], verbose_name='Admissão'),
        ),
    ]
