# Generated by Django 5.0 on 2025-12-05 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0009_alter_professor_admissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(help_text='Insira a matrícula do Aluno', max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='Matrícula')),
                ('nome', models.CharField(help_text='Insira o nome do Aluno', max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nome')),
                ('ingresso', models.DateField(help_text='Digite a data de ingresso', verbose_name='Ingresso')),
                ('email', models.EmailField(help_text='Digite o e-mail do aluno', max_length=254, unique=True, verbose_name='E-mail')),
                ('formando', models.BooleanField(default=False, help_text='Marque se o Aluno está se formando', verbose_name='Formando ?')),
                ('bolsista', models.DecimalField(decimal_places=2, help_text='Insira o valor da bolsa', max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor total da bolsa do Aluno')),
                ('nascimento', models.DateField(help_text='Insira a data de nascimento', verbose_name='Data de nascimento do atleta')),
                ('media', models.FloatField(help_text='Digite o rendimento do Aluno', verbose_name='Rendimento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)])),
                ('nivel', models.CharField(choices=[('Basico', 'Básico'), ('Tecnico', 'Técnico'), ('Superior', 'Superior'), ('Pos-Graduacao', 'Pós-Graduação')], default='Superior', help_text='Escolha o nível do curso', max_length=30, verbose_name='Curso')),
                ('duracao', models.IntegerField(help_text='Digite a duração do período letivo', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)], verbose_name='Período')),
                ('periodo_letivo', models.CharField(choices=[('Semestral', 'Semetral'), ('Anual', 'Anual'), ('Modular', 'Modular')], default='Semestral', help_text='Escolha o período letivo do Aluno', max_length=30, verbose_name='Período')),
                ('turno', models.CharField(choices=[('Manha', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], default='Noite', help_text='Escolha o turno do Aluno', max_length=30, verbose_name='Turno')),
                ('campus', models.CharField(choices=[('POA', 'Campus Porto Alegre'), ('Restinga', 'Campus Restinga'), ('Rolante', 'Campus Rolante'), ('POA Zona Norte', 'Campus POA Zona Norte')], default='POA', help_text='Digite o campus de sua escolha', max_length=30, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Campus')),
                ('nota_mec', models.FloatField(help_text='Digite a nota do curso', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nota MEC')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
