# Generated by Django 5.0 on 2025-12-08 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0010_aluno_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o nome da Disciplina', max_length=30, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Disciplina')),
                ('creditos', models.IntegerField(help_text='Digite os creditos da disciplina', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Créditos')),
                ('carga_horaria', models.IntegerField(help_text='Digite a carga horária da disciplina', validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(160)], verbose_name='Carga Horária')),
                ('modalidade', models.CharField(choices=[('EAD', 'EAD'), ('SEMI-PRESENCIAL', 'SEMI-PRESENCIAL'), ('PRESENCIAL', 'PRESENCIAL')], help_text='Digite a modalidade da disciplima', max_length=50, verbose_name='Modalidade')),
                ('data_inicio', models.DateField(help_text='Digite a data de inicio da disciplina', verbose_name='Data inicio')),
                ('data_fim', models.DateField(help_text='Digite a data de termino da disciplina', verbose_name='Data fim')),
                ('ementa', models.TextField(help_text='Digite a ementa da disciplina', verbose_name='Ementa')),
                ('fechada', models.BooleanField(default=True, help_text='A disciplina está desativada ?', verbose_name='Disciplina fechada')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
