# Generated by Django 5.0 on 2025-12-08 19:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0011_disciplina_alter_curso_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='ementa',
            field=models.TextField(help_text='Digite a ementa da disciplina', max_length=2000, validators=[django.core.validators.MinLengthValidator(50)], verbose_name='Ementa'),
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingresso', models.DateField(help_text='Data de ingresso do aluna na disciplina', verbose_name='Ingresso')),
                ('fim', models.DateField(help_text='Data de encerramento do hstorico do aluno', verbose_name='Fim')),
                ('nota', models.DecimalField(decimal_places=2, help_text='Nota do aluno na disciplina', max_digits=4, verbose_name='TESTE')),
                ('presenca', models.FloatField(help_text='Percemtual de frequência do aluno, entre 0--100', verbose_name='Frequência')),
                ('status', models.CharField(choices=[('Em andamento', 'Em andamento'), ('Reprovado por nota', 'Reprovado por nota'), ('Reprovado por frequência', 'Reprovado por frequência'), ('Aprovado', 'Aprovado'), ('Aprovado por exame', 'Aprovado por exame'), ('Em exame', 'Em exame')], default=True, help_text='Selecione o status do aluno na disciplina', max_length=30, verbose_name='Status')),
                ('aluno', models.ForeignKey(help_text='Selecione um aluno', on_delete=django.db.models.deletion.RESTRICT, to='digital.aluno', verbose_name='Aluno')),
                ('disciplina', models.ForeignKey(help_text='Seleciona uma disciplina', on_delete=django.db.models.deletion.RESTRICT, to='digital.disciplina', verbose_name='Disciplina')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, null=True, through='digital.Historico', to='digital.disciplina'),
        ),
    ]
