# Generated by Django 5.0 on 2026-01-16 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0012_alter_disciplina_ementa_historico_aluno_disciplinas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='escritorio',
            field=models.OneToOneField(help_text='Escolha o escritório', on_delete=django.db.models.deletion.CASCADE, to='digital.escritorio', verbose_name='Escritório'),
        ),
    ]
