from .base_model import *
from .exemplo import *
from .atleta import *
from .escritorio import *
from .professor import *
from .curso import *
from .disciplina import *
from .aluno import *
from .historico import *