# Generated by Django 4.2.11 on 2025-12-12 15:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o nome do evento', max_length=100, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, help_text='Digite a descrição do evento', validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(1000)], verbose_name='Descrição')),
                ('data', models.DateField(default=django.utils.timezone.now, help_text='Digite a data do evento', verbose_name='Data evento')),
                ('time', models.TimeField(default=django.utils.timezone.now, help_text='Digite a hora do evento', verbose_name='Hora evento')),
                ('tipo_evento', models.CharField(choices=[('Jogo', 'Jogo'), ('Show de Música', 'Show de Música'), ('Outros', 'Outros')], help_text='Escolha o tipo de evento', max_length=20, verbose_name='Tipo evento')),
                ('capacidade', models.IntegerField(help_text='Digite a capacidade do evento', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(60000)], verbose_name='Capacidade evento')),
                ('cobertura_campo', models.BooleanField(default=False, help_text='Marque se o evento possui uma cobertura', verbose_name='Evento tem cobertura')),
                ('organizador', models.CharField(help_text='Digite o nome do organizador do evento', max_length=100, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Organizador do evento')),
                ('ingressos_disponiveis', models.IntegerField(help_text='Digite a quantidade de ingressos disponíveis', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ingressos disponíveis')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ingresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o nome do ingresso', max_length=150, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Nome do ingresso')),
                ('email', models.EmailField(help_text='Digite o e-mail do comprador', max_length=254, verbose_name='E-mail do comprador')),
                ('preco', models.FloatField(help_text='Digite o preço do ingresso', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço do ingresso')),
                ('tipo_ingresso', models.CharField(choices=[('Inteira', 'Inteira'), ('Meia Entrada', 'Meia Entrada'), ('Vip', 'Vip')], help_text='Selecione o tipo de ingresso', max_length=20, verbose_name='Tipo de ingresso')),
                ('pagamento', models.CharField(choices=[('Cartão de Crédito', 'Cartão de Crédito'), ('Dinheiro', 'Dinheiro'), ('Pix', 'Pix')], help_text='Selecione o tipo de pagamento', max_length=20, verbose_name='Tipo de pagamento')),
                ('checkin', models.BooleanField(default=False, help_text='Marque se o ingresso está válido para uso', verbose_name='Check-in')),
                ('acesso', models.DateTimeField(blank=True, help_text='Data e hora em que o ingresso foi utilizado', null=True, verbose_name='Data e hora de acesso')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerencia_eventos.evento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Digite o código do assento', max_length=3, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Código do assento')),
                ('bloco', models.IntegerField(help_text='Digite o número do bloco onde o assento está localizado', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Bloco do assento')),
                ('setor', models.CharField(choices=[('Arquibancada', 'Arquibancada'), ('Cadeira', 'Cadeira'), ('Camarote', 'Camarote'), ('Pista', 'Pista')], help_text='Selecione o setor do assento', max_length=20, verbose_name='Setor do assento')),
                ('disponivel', models.BooleanField(default=False, help_text='Marque se o assento está disponível', verbose_name='Assento disponível')),
                ('preco', models.FloatField(help_text='Digite o valor do assento', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Valor do assento')),
                ('acessibilidade', models.BooleanField(default=False, help_text='Marque se o assento possui acessibilidade', verbose_name='Acessível')),
                ('ultima_manutencao', models.DateField(blank=True, help_text='Digite a data da última manutenção', null=True, verbose_name='Data da última manutenção')),
                ('ingresso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gerencia_eventos.ingresso')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
