# Generated by Django 4.2.11 on 2025-12-13 22:10

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia_eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresso',
            name='data_compra',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora da compra do ingresso', verbose_name='Data da compra'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.TextField(blank=True, help_text='Digite a descrição do evento', null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(1000)], verbose_name='Descrição'),
        ),
    ]
