# Generated by Django 4.2.11 on 2025-12-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia_eventos', '0002_ingresso_data_compra_alter_evento_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresso',
            name='pagamento',
            field=models.CharField(blank=True, choices=[('Cartão de Crédito', 'Cartão de Crédito'), ('Dinheiro', 'Dinheiro'), ('Pix', 'Pix')], help_text='Selecione o tipo de pagamento', max_length=20, null=True, verbose_name='Tipo de pagamento'),
        ),
    ]
