# Generated by Django 4.2.11 on 2026-01-05 13:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canal_id', models.CharField(help_text='Digite o ID do canal.', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Canal ID')),
                ('canal_nome', models.CharField(help_text='Digite o nome do canal.', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Nome do canal')),
                ('canal_inscritos', models.IntegerField(help_text='Digite a quantidade de inscritos do canal.', verbose_name='Quantidade de inscritos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(help_text='Digite o nome da categoria', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Categoria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('playlist_id', models.CharField(help_text='Digite o ID da playlist.', max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='Playlist ID')),
                ('playlist_nome', models.CharField(help_text='Digite o nome da playlist.', max_length=50, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Nome Playlist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_id', models.CharField(help_text='Digite o ID do vídeo.', max_length=10, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='ID do vídeo')),
                ('url', models.CharField(help_text='Digite a URL do vídeo.', max_length=100, validators=[django.core.validators.MinLengthValidator(40)], verbose_name='URL do vídeo')),
                ('titulo', models.CharField(help_text='Digite o título do vídeo.', max_length=100, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Título do Vídeo')),
                ('likes', models.IntegerField(help_text='Digite a quantidade de likes do vídeo.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Likes do Vídeo')),
                ('deslikes', models.IntegerField(help_text='Digite a quantidade de deslikes do vídeo.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Deslikes do Vídeo')),
                ('salvos', models.IntegerField(help_text='Digite a quantas vezes o vídeo foi salvo.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Salvos do vídeo')),
                ('downloads', models.IntegerField(help_text='Digite a quantidade de vezes que p vídeo foi baixado.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Downloads do Vídeo')),
                ('duracao', models.TimeField(help_text='Digite a duração do vídeo', verbose_name='Duração do Vídeo')),
                ('comentarios', models.IntegerField(help_text='Digite a quantidade de comentários do vídeo', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Comentários do vídeo')),
                ('qualidade_px', models.CharField(choices=[('360', '360'), ('480', '480'), ('720', '720'), ('1080', '1080'), ('1440', '1440'), ('2160', '2160')], help_text='Selecione a qualidade do vídeo', max_length=4, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Qualidade')),
                ('palavras_chaves', models.JSONField(help_text='Digite as palavras-chave do vídeo', verbose_name='Palavras-chave')),
                ('descricao', models.TextField(blank=True, help_text='Digite a descrição do vídeo', validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Descrição do Vídeo')),
                ('data_postagem', models.DateField(help_text='Digite a data da postagem do vídeo', verbose_name='Data da postagem')),
                ('idioma', models.CharField(choices=[('pt-BR', 'Portugues Brasileiro'), ('pt-PT', 'Portugues'), ('es', 'Espanhol'), ('en', 'Ingles')], help_text='Selecione o idioma do vídeo', max_length=5, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Idioma')),
                ('visibilidade', models.CharField(choices=[('PUBLICO', 'PUBLICO'), ('PRIVADO', 'PRIVADO')], help_text='Selecione a visibilidade do vídeo', max_length=7, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='Visibilidade')),
                ('canal', models.ForeignKey(help_text='Selecione o canal', on_delete=django.db.models.deletion.CASCADE, to='gerencia_youtube.canal', verbose_name='Canal')),
                ('categorias', models.ManyToManyField(help_text='Selecione as categorias', to='gerencia_youtube.categoria', verbose_name='Categorias')),
                ('playlists', models.ManyToManyField(help_text='Selecione uma playlist', to='gerencia_youtube.playlist', verbose_name='Playlist')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
