# Generated by Django 4.2.11 on 2026-01-05 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia_youtube', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_id',
            field=models.CharField(help_text='Digite o ID da playlist.', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='Playlist ID'),
        ),
    ]
