# Generated by Django 4.2.11 on 2026-01-05 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia_youtube', '0002_alter_playlist_playlist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(help_text='Digite o ID do vídeo.', max_length=20, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='ID do vídeo'),
        ),
    ]
