# Generated by Django 4.2.11 on 2026-01-05 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia_youtube', '0003_alter_video_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='idioma',
            field=models.CharField(choices=[('pt-BR', 'Portugues (Brasil)'), ('pt-PT', 'Portugues'), ('es', 'Espanhol'), ('en', 'Ingles')], help_text='Selecione o idioma do vídeo', max_length=5, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Idioma'),
        ),
    ]
