# Generated by Django 4.2.11 on 2026-01-06 23:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia_youtube', '0004_alter_video_idioma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canal',
            name='canal_nome',
            field=models.CharField(help_text='Digite o nome do canal.', max_length=50, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Nome do canal'),
        ),
    ]
