# Generated by Django 4.2.11 on 2026-01-25 01:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import gestao.validators.inicio_projeto_validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(help_text='Digite o código do projeto', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Código do Projeto')),
                ('nome', models.CharField(help_text='Digite o nome do projeto', max_length=100, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Nome do Projeto')),
                ('tipo_projeto', models.CharField(choices=[('Desenvolvimento Web', 'Desenvolvimento Web'), ('Aplicativo de Celular', 'Aplicativo de Celular'), ('Aplicação Desktop', 'Aplicação Desktop'), ('Web Services/API', 'Web Services/API'), ('Biblioteca/SDK', 'Biblioteca/SDK'), ('Projeto de Ciência de Dados', 'Projeto de Ciência de Dados'), ('Inteligência Artificial', 'Inteligência Artificial')], help_text='Selecione o tipo do projeto', max_length=30, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Tipo do Projeto')),
                ('cliente', models.CharField(help_text='Digite o nome do cliente', max_length=50, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nome do Cliente')),
                ('gerente', models.CharField(help_text='Digite o nome do gerente', max_length=50, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nome do Gerente')),
                ('inicio', models.DateField(help_text='Insira a data de início do projeto', validators=[gestao.validators.inicio_projeto_validator.InicioProjetoValidator()], verbose_name='Data de Início do Projeto')),
                ('previsao_termino', models.DateField(help_text='Insira a data para a previsão de finalização do projeto', verbose_name='Previsã de Finalização do Projeto')),
                ('fim', models.DateField(blank=True, help_text='Insira a data de finalização do projeto', null=True, verbose_name='Data do Fim do Projeto')),
                ('orcamento', models.DecimalField(decimal_places=2, help_text='Insira o orçamento do projeto', max_digits=8, verbose_name='Orçamento do Projeto')),
                ('ativo', models.BooleanField(default=True, help_text='Marque se o projeto está ATIVO ou DESATIVADO', verbose_name='Situação do Proeto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(help_text='Digite o título da tarefa', max_length=100, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Título da Tarefa')),
                ('descricao', models.TextField(blank=True, help_text='Digite a descrição da tarefa', null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(1000)], verbose_name='Descrição da Tarefa')),
                ('linguagem', models.CharField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('Java', 'Java'), ('C#', 'C#'), ('C++', 'C++'), ('C', 'C'), ('Php', 'Php'), ('Dart', 'Dart')], help_text='Seleciona a Linguagem de Programação', max_length=12, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Tipo de Linguagem')),
                ('estimativa_horas', models.IntegerField(help_text='Digite a estimativa de horas para realizar a tarefa', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estimativa de Horas para Tarefa')),
                ('horas_registradas', models.IntegerField(help_text='Digite as horas registradas da tarefa', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Horas Registradas da Tarefa')),
                ('prioridade', models.IntegerField(help_text='Digite a prioridade da tarefa (1 - 5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Prioridade da Tarefa')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Em andamento', 'Em andamento'), ('Concluído', 'Concluído'), ('Bloqueado', 'Bloqueado'), ('Atrasado', 'Atrasado')], help_text='Selecione o Status da tarefa', max_length=14, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Status da Tarefa')),
                ('responsavel', models.CharField(help_text='Digite o responsável pela tarefa', max_length=50, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Digite o Responsável')),
                ('criacao', models.DateTimeField(help_text='Insira a data da criação da tarefa', verbose_name='Data da Criação da Tarefa')),
                ('conclusao', models.DateTimeField(blank=True, help_text='Insira a data da conclusão da tarefa', null=True, verbose_name='Data da conclusão da Tarefa')),
                ('projeto', models.ForeignKey(help_text='Selecione um projeto', on_delete=django.db.models.deletion.CASCADE, to='gestao.projeto', verbose_name='Projeto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
