# Generated by Django 4.2.11 on 2026-01-25 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='projeto',
            field=models.ForeignKey(help_text='Selecione um projeto', on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='gestao.projeto', verbose_name='Projeto'),
        ),
    ]
